name: egd-radiomics
channels:
  - conda-forge
  - radiomics
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas
  - scipy
  - scikit-learn=1.5.2
  - matplotlib
  - openpyxl
  - pyyaml
  - simpleitk
  - pywavelets
  - ipykernel
  - jupyter
  - pyradiomics=3.0.1
